import CliLayout from "@components/cli/CliLayout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@styles/CLI.module.scss";

export default function CLI() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CLI &#45; Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      overview cli content
    </div>
  );
}

// TODO: fix
// eslint-disable-next-line react/display-name
CLI.getLayout = (page) => <CliLayout>{page}</CliLayout>;
