import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "@sequelize/core";
import { nanoid } from "nanoid";

import { sequelize } from "../sequelize";

export type Permission = string;

export class Role extends Model<
  InferAttributes<Role>,
  InferCreationAttributes<Role>
> {
  declare id: CreationOptional<string>; // id can be undefined during creation (generated by nanoid)
  declare name: string;

  declare permissions: Permission[] | null;

  // timestamps
  declare createdAt: CreationOptional<Date>; // createdAt can be undefined during creation
  declare updatedAt: CreationOptional<Date>; // updatedAt can be undefined during creation
}

Role.init(
  {
    id: {
      type: DataTypes.STRING,
      allowNull: false,
      primaryKey: true,
      unique: true,
      defaultValue: () => nanoid(),
    },
    name: DataTypes.STRING,
    permissions: DataTypes.ARRAY(DataTypes.STRING),
    createdAt: DataTypes.DATE,
    updatedAt: DataTypes.DATE,
  },
  {
    sequelize,
    modelName: "Role",
  }
);
