import { Description, Tabs } from "@components/design";

import CmsLayout from "@components/cms/CmsLayout";
import CmsWork from "@components/cms/CmsWork";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Spacer } from "@components/design";
import { Work } from "@lib/sequelize";
import styled from "styled-components";
import styles from "@styles/CMS.module.scss";

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
`;

const Text = styled.span``;

export default function CMS({ works }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CMS &#45; Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>test</Title>

      <Spacer />

      <Tabs initialValue="1">
        <Tabs.Item label="Home" value="1">
          <Text>Hello!</Text>
        </Tabs.Item>
        <Tabs.Item label="About" value="2">
          <Text>Cool stuff.</Text>
        </Tabs.Item>
        <Tabs.Item label="About Us" value="3">
          <Text>Good people.</Text>
        </Tabs.Item>
        <Tabs.Item label="Features" value="4">
          <Text>Amazing.</Text>
        </Tabs.Item>
        <Tabs.Item label="Pricing" value="5">
          <Text>Very low.</Text>
        </Tabs.Item>
        <Tabs.Item label="Docs" value="6">
          <Text>Clear.</Text>
        </Tabs.Item>
        <Tabs.Item label="Profile" value="7">
          <Text>Extraordinary person.</Text>
        </Tabs.Item>
        <Tabs.Item label="Settings" value="8">
          <Text>Easy to tweak.</Text>
        </Tabs.Item>
        <Tabs.Item label="Dashboard" value="9">
          <Text>Charts.</Text>
        </Tabs.Item>
        <Tabs.Item label="Policies" value="10">
          <Text>Privacy focused.</Text>
        </Tabs.Item>
      </Tabs>

      <Spacer />

      <Description title="Section Title" content="Data about this section." />

      <Spacer />

      {works.map((work) => (
        <CmsWork key={work.id} work={work} />
      ))}
    </div>
  );
}

export async function getServerSideProps(_context) {
  const works = await Work.findAll({ raw: true });
  // console.log(works, JSON.stringify(works));
  return {
    props: { works }, // will be passed to the page component as props
  };
}

// TODO: fix
// eslint-disable-next-line react/display-name
CMS.getLayout = (page) => <CmsLayout>{page}</CmsLayout>;
