import { Description, Grid, Spacer, Tabs } from "@geist-ui/react";

import CmsLayout from "@components/cms/CmsLayout";
import CmsWork from "@components/cms/CmsWork";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Work } from "@lib/sequelize";
import { createDeflate } from "zlib";
import { serialize } from "superjson";
import styled from "styled-components";
import styles from "@styles/CMS.module.scss";

// import type { GetStaticProps, InferGetStaticPropsType } from 'next';

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
`;

const Text = styled.span``;

export default function CMS({ works }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CMS &#45; Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>test</Title>
      <Spacer />
      <Description title="Section Title" content="Data about this section." />
      <Spacer />
      <Grid.Container gap={2} justify="center">
        {/* works.flatMap((work, i) => [
          <CmsWork key={work.id} work={work} />,
          <Spacer key={i} />,
        ]) */}
        {works?.length > 0 ? (
          <>
            {works.map((work) => (
              <Grid key={work.id} xs={24} md={12} lg={8}>
                <CmsWork key={work.id} work={work} />
              </Grid>
            ))}
          </>
        ) : (
          <>no works found</>
        )}
      </Grid.Container>
    </div>
  );
}

export async function getServerSideProps(_context) {
  let works = await Work.findAll();

  works = works.map((work) => serialize(work.get({ plain: true })));

  console.log(works);

  // console.log(works, JSON.stringify(works));
  return {
    props: { works }, // will be passed to the page component as props
  };
}

// TODO: fix
// eslint-disable-next-line react/display-name
CMS.getLayout = (page) => <CmsLayout>{page}</CmsLayout>;
